---
abstract: 'entropy (randomness) management'
author:
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.72, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Entropy
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Crypt::Rijndael: '0'
  Crypt::URandom: '0.36'
  Data::Float: '0.008'
  Errno: '1.00'
  Exporter: '0'
  HTTP::Lite: '2.2'
  IO::File: '1.03'
  Module::Build: '0'
  Params::Classify: '0'
  Test::More: '0'
  constant: '0'
  integer: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/robrwo/Data-Entropy/issues
  repository: git://github.com/robrwo/Data-Entropy.git
version: '0.008'
x_deprecated: 1
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
